module Const{
	export const MODULE_EVALUATE:string="evaluate"


	export enum Server{
		SU_DI_CHUN_XIAO=137
	}

    export enum Kind{
		ALL=0,//全部
        COIN=23,//梦幻币
        ROLE=27,//角色
        PET=1,//召唤兽
        ITEM=2,//道具类
        SCHOOL_DT=30,//大唐官府
        SCHOOL_LG=36,//龙宫
        SCHOOL_HS=31,//化生寺
        SCHOOL_PS=41,//盘丝洞
        SCHOOL_PT=35,//普陀山
        SCHOOL_TG=34,//天宫
        SCHOOL_NE=32,//女儿村
        SCHOOL_WD=51,//无底洞
        SCHOOL_WZ=37,//五庄观
        SCHOOL_FC=33,//方寸山
        SCHOOL_LBC=50,//凌波城
        SCHOOL_MW=39,//魔王寨
        SCHOOL_DF=40,//阴曹地府
        SCHOOL_ST=38,//狮驼岭
        SCHOOL_SML=49,//神木林
        SCHOOL_NBM=77,//女魃墓
        SCHOOL_TJC=78,//天机城
        SCHOOL_HGS=79,//花果山
        PET_SS=71,//神兽
        PET_45_65=65,//参战45-65
        PET_75_105=66,//参战75-105
        PET_125_145=67,//参战125-145
        PET_FS_120_155=68,//飞升120-155
        PET_DJ_155_175=69,//渡劫155-175
        PET_HS_175=75,//化圣175
        PET_GXC=70,//个性宠
        EQUIP_WQ=57,//武器
        EQUIP_FJ=55,//防具
        EQUIP_LS=60,//灵饰
        EQUIP_QT=56,//其他
        EQUIP_JIAN=6,//剑
        EQUIP_QIANG=4,//枪矛
        EQUIP_SHANZI=10,//扇
        EQUIP_DAO=14,//刀
        EQUIP_FUYUE=5,//斧钺
        EQUIP_BANGZI=11,//魔棒
        EQUIP_PIAODAI=8,//飘带
        EQUIP_ZHUACI=9,//爪刺
        EQUIP_JUJIAN=73,//巨剑
        EQUIP_SHAN=74,//伞
        EQUIP_CHUI=15,//锤
        EQUIP_SHUANGJIAN=7,//双短剑
        EQUIP_DENGLONG=72,//灯笼
        EQUIP_HUANQUAN=13,//环圈
        EQUIP_GONG=53,//弓箭
        EQUIP_BIAN=12,//鞭
        EQUIP_ZHANG=54,//法杖
        EQUIP_BAOZHU=52,//宝珠
        EQUIP_YAODAI=20,//腰带
        EQUIP_XIEZI=19,//鞋子
        EQUIP_TOUKUI=17,//头盔
        EQUIP_SHIWU=21,//饰物
        EQUIP_KAIJIA=18,//铠甲
        EQUIP_NVYI=59,//女衣
        EQUIP_FACHAI=58,//发钗
        EQUIP_JIEZHI=61,//戒指
        EQUIP_SHOUZHUO=63,//手镯
        EQUIP_ERSHI=62,//耳饰
        EQUIP_PEISHI=64,//佩饰
        EQUIP_PET=29,//召唤兽装备
        ITEM_CAILIAO=29,//材料
        ITEM_SHOUJUE=27,//魔兽要诀
        ITEM_NEIDAN=43,//召唤兽内丹
    }


    export const KEY_ADDON_EFFECT_CHANCE:string="addon_effect_chance"
	export const KEY_ADDON_FALI:string="addon_fali"
	export const KEY_ADDON_LILIANG:string="addon_liliang"
	export const KEY_ADDON_LINGLI:string="addon_lingli"
	export const KEY_ADDON_MINJIE:string="addon_minjie"
	export const KEY_ADDON_NAILI:string="addon_naili"
	export const KEY_ADDON_SKILL_CHANCE:string="addon_skill_chance"
	export const KEY_ADDON_STATUS:string="addon_status"
	export const KEY_ADDON_TIZHI:string="addon_tizhi"
	export const KEY_ADDON_TOTAL:string="addon_total"
	export const KEY_ANTI_FENGYIN:string="anti_fengyin"
	export const KEY_APPOINTED_ROLEID:string="appointed_roleid"
	export const KEY_AREA_NAME:string="area_name"
	export const KEY_BB_EXPT_FANGYU:string="bb_expt_fangyu"
	export const KEY_BB_EXPT_FASHU:string="bb_expt_fashu"
	export const KEY_BB_EXPT_GONGJI:string="bb_expt_gongji"
	export const KEY_BB_EXPT_KANGFA:string="bb_expt_kangfa"
	export const KEY_COLLECT_NUM:string="collect_num"
	export const KEY_CREATE_TIME:string="create_time"
	export const KEY_DAMAGE:string="damage"
	export const KEY_DEFENSE:string="defense"
	export const KEY_DESC0:string="desc0"
	export const KEY_DESC:string="desc"
	export const KEY_EID:string="eid"
	export const KEY_EQUIP_COUNT:string="equip_count"
	export const KEY_EQUIP_FACE_IMG:string="equip_face_img"
	export const KEY_EQUIP_LEVEL:string="equip_level"
	export const KEY_EQUIP_LEVEL_DESC:string="equip_level_desc"
	export const KEY_EQUIP_NAME:string="equip_name"
	export const KEY_EQUIP_TYPE:string="equip_type"
	export const KEY_EQUIP_TYPE_DESC:string="equip_type_desc"
	export const KEY_EQUIPID:string="equipid"
	export const KEY_EXPIRE_TIME:string="expire_time"
	export const KEY_EXPT_FANGYU:string="expt_fangyu"
	export const KEY_EXPT_FASHU:string="expt_fashu"
	export const KEY_EXPT_GONGJI:string="expt_gongji"
	export const KEY_EXPT_KANGFA:string="expt_kangfa"
	export const KEY_FAIR_SHOW_END_TIME_LEFT:string="fair_show_end_time_left"
	export const KEY_FANGYU:string="fangyu"
	export const KEY_FENGYIN:string="fengyin"
	export const KEY_GAME_ORDERSN:string="game_ordersn"
	export const KEY_GEM_LEVEL:string="gem_level"
	export const KEY_GEM_VALUE:string="gem_value"
    export const KEY_highlights:string="highLIGHTS"
	export const KEY_HP:string="hp"
	export const KEY_ICON:string="icon"
	export const KEY_IS_COLLECT:string="is_collect"
	export const KEY_JINGLIAN_LEVEL:string="jinglian_level"
	export const KEY_KINDID:string="kindid"
	export const KEY_LEVEL:string="level"
	export const KEY_LINGLI:string="lingli"
	export const KEY_MAGIC_DAMAGE:string="magic_damage"
	export const KEY_MAGIC_DEFENSE:string="magic_defense"
	export const KEY_MAX_EXPT_FANGYU:string="max_expt_fangyu"
	export const KEY_MAX_EXPT_FASHU:string="max_expt_fashu"
	export const KEY_MAX_EXPT_GONGJI:string="max_expt_gongji"
	export const KEY_MAX_EXPT_KANGFA:string="max_expt_kangfa"
	export const KEY_MIN_BUYER_LEVEL:string="min_buyer_level"
	export const KEY_MINGZHONG:string="mingzhong"
	export const KEY_MINJIE:string="minjie"
	export const KEY_MOFA:string="mofa"
	export const KEY_OTHER_INFO:string="other_info"
	export const KEY_OTHER_INFO0:string="other_info0"
	export const KEY_PRICE:string="price"
	export const KEY_PRICE_INT:string="price_int"
	export const KEY_QIXUE:string="qixue"
	export const KEY_SCHOOL:string="school"
	export const KEY_SCORE:string="score"
	export const KEY_SELLER_NICKNAME:string="seller_nickname"
	export const KEY_SELLER_ROLEID:string="seller_roleid"
	export const KEY_SELLING_TIME:string="selling_time"
	export const KEY_SERVER_ID:string="server_id"
	export const KEY_SERVER_NAME:string="server_name"
	export const KEY_SERVER_SN:string="server_sn"
	export const KEY_SERVERID:string="serverid"
	export const KEY_SHANGHAI:string="shanghai"
	export const KEY_SPECIAL_EFFECT:string="special_effect"
	export const KEY_SPECIAL_SKILL:string="special_skill"
	export const KEY_SPEED:string="speed"
	export const KEY_STATUS:string="status"
	export const KEY_STORAGE_TYPE:string="storage_type"
	export const KEY_SUIT_EFFECT:string="suit_effect"
	export const KEY_SUIT_SKILL:string="suit_skill"
	export const KEY_TAG:string="tag"
	export const KEY_TIME_LEFT:string="time_left"
	export const KEY_UNIT_PRICE_DESC:string="unit_price_desc"
	export const KEY_XIANG_QIAN_LEVEL:string="xiang_qian_level"
	export const KEY_ZONGSHANG:string="zongshang"
    
    export const DESC_ACHPOINTTOTAL:string="AchPointTotal"
	export const DESC_ADDPOINT:string="addPoint"
	export const DESC_ALL_SKILLS:string="all_skills"
	export const DESC_ALLEQUIP:string="AllEquip"
	export const DESC_ALLRIDER:string="AllRider"
	export const DESC_ALLSUMMON:string="AllSummon"
	export const DESC_BID:string="bid"
	export const DESC_CHANGESCH:string="changesch"
	export const DESC_CNAME:string="cName"
	export const DESC_COMMU_GID:string="commu_gid"
	export const DESC_COMMU_NAME:string="commu_name"
	export const DESC_CORG:string="cOrg"
	export const DESC_DATANG_FEAT:string="datang_feat"
	export const DESC_ENERGY:string="energy"
	export const DESC_EXAVT:string="ExAvt"
	export const DESC_EXPJW:string="ExpJw"
	export const DESC_EXPJWBASE:string="ExpJwBase"
	export const DESC_FABAO:string="fabao"
	export const DESC_FARM_LEVEL:string="farm_level"
	export const DESC_HEROSCORE:string="HeroScore"
	export const DESC_HUGEHORSE:string="HugeHorse"
	export const DESC_I3FLYLV:string="i3FlyLv"
	export const DESC_IATT_ALL:string="iAtt_All"
	export const DESC_IBADNESS:string="iBadness"
	export const DESC_IBEASTSKI1:string="iBeastSki1"
	export const DESC_IBEASTSKI2:string="iBeastSki2"
	export const DESC_IBEASTSKI3:string="iBeastSki3"
	export const DESC_IBEASTSKI4:string="iBeastSki4"
	export const DESC_ICASH:string="iCash"
	export const DESC_ICGBODYAMOUNT:string="iCGBodyAmount"
	export const DESC_ICGBOXAMOUNT:string="iCGBoxAmount"
	export const DESC_ICGTOTALAMOUNT:string="iCGTotalAmount"
	export const DESC_ICOLOR_EX:string="icolor_ex"
	export const DESC_ICOR_ALL:string="iCor_All"
	export const DESC_IDAMAGE_ALL:string="iDamage_All"
	export const DESC_IDBID_DESC:string="idbid_desc"
	export const DESC_IDEF_ALL:string="iDef_All"
	export const DESC_IDESC:string="iDesc"
	export const DESC_IDEX_ALL:string="iDex_All"
	export const DESC_IDOD_ALL:string="iDod_All"
	export const DESC_IERRANTRY:string="iErrantry"
	export const DESC_IEXPTSKI1:string="iExptSki1"
	export const DESC_IEXPTSKI2:string="iExptSki2"
	export const DESC_IEXPTSKI3:string="iExptSki3"
	export const DESC_IEXPTSKI4:string="iExptSki4"
	export const DESC_IEXPTSKI5:string="iExptSki5"
	export const DESC_IGOODNESS:string="iGoodness"
	export const DESC_IGOODNESS_SAV:string="igoodness_sav"
	export const DESC_IGRADE:string="iGrade"
	export const DESC_IHP:string="iHp"
	export const DESC_IHP_EFF:string="iHp_Eff"
	export const DESC_IHP_MAX:string="iHp_Max"
	export const DESC_IICON:string="iIcon"
	export const DESC_ILEARNCASH:string="iLearnCash"
	export const DESC_IMAG_ALL:string="iMag_All"
	export const DESC_IMAGDEF_ALL:string="iMagDef_All"
	export const DESC_IMARRY:string="iMarry"
	export const DESC_IMARRY2:string="iMarry2"
	export const DESC_IMAXEXPT1:string="iMaxExpt1"
	export const DESC_IMAXEXPT2:string="iMaxExpt2"
	export const DESC_IMAXEXPT3:string="iMaxExpt3"
	export const DESC_IMAXEXPT4:string="iMaxExpt4"
	export const DESC_IMP:string="iMp"
	export const DESC_IMP_MAX:string="iMp_Max"
	export const DESC_INUTSNUM:string="iNutsNum"
	export const DESC_IORGOFFER:string="iOrgOffer"
	export const DESC_IPCKTPAGE:string="iPcktPage"
	export const DESC_IPOINT:string="iPoint"
	export const DESC_IPRIDE:string="iPride"
	export const DESC_IRACE:string="iRace"
	export const DESC_IRES_ALL:string="iRes_All"
	export const DESC_ISAVING:string="iSaving"
	export const DESC_ISCHOFFER:string="iSchOffer"
	export const DESC_ISCHOOL:string="iSchool"
	export const DESC_ISEWSKI:string="iSewski"
	export const DESC_ISKIPOINT:string="iSkiPoint"
	export const DESC_ISMITHSKI:string="iSmithski"
	export const DESC_ISPE_ALL:string="iSpe_All"
	export const DESC_ISTR_ALL:string="iStr_All"
	export const DESC_ISUMAMOUNT:string="iSumAmount"
	export const DESC_ISUMAMOUNTEX:string="iSumAmountEx"
	export const DESC_ITOTALMAGDAM_ALL:string="iTotalMagDam_all"
	export const DESC_ITOTALMAGDEF_ALL:string="iTotalMagDef_all"
	export const DESC_IUPEXP:string="iUpExp"
	export const DESC_IZHUANZHI:string="iZhuanZhi"
	export const DESC_JIYUAN:string="jiyuan"
	export const DESC_MORE_ATTR:string="more_attr"
	export const DESC_NORMAL_HORSE:string="normal_horse"
	export const DESC_ORI_DESC:string="ori_desc"
	export const DESC_ORI_RACE:string="ori_race"
	export const DESC_OUTDOOR_LEVEL:string="outdoor_level"
	export const DESC_PET:string="pet"
	export const DESC_PROPKEPT:string="propKept"
	export const DESC_RENT:string="rent"
	export const DESC_RENT_LEVEL:string="rent_level"
	export const DESC_SHENQI:string="shenqi"
	export const DESC_SHENQI_POS:string="shenqi_pos"
	export const DESC_SHENQI_YELLOW:string="shenqi_yellow"
	export const DESC_SUM_EXP:string="sum_exp"
	export const DESC_SWORD_SCORE:string="sword_score"
	export const DESC_TA_IALLNEWPOINT:string="TA_iAllNewPoint"
	export const DESC_TA_IALLPOINT:string="TA_iAllPoint"
	export const DESC_TOTAL_AVATAR:string="total_avatar"
	export const DESC_TOTAL_HORSE:string="total_horse"
	export const DESC_USERNUM:string="usernum"
	export const DESC_XIANYU:string="xianyu"

    export const OTHER_ACHPOINTTOTAL:string="AchPointTotal"
	export const OTHER_ADD_MELT_ATTRS:string="add_melt_attrs"
	export const OTHER_ALL_SKILLS:string="all_skills"
	export const OTHER_CNAME:string="cName"
	export const OTHER_EXPJW:string="ExpJw"
	export const OTHER_EXPJWBASE:string="ExpJwBase"
	export const OTHER_HIGHLIGHT:string="highlight"
	export const OTHER_I3FLYLV:string="i3FlyLv"
	export const OTHER_IBADNESS:string="iBadness"
	export const OTHER_IBEASTSKI1:string="iBeastSki1"
	export const OTHER_IBEASTSKI2:string="iBeastSki2"
	export const OTHER_IBEASTSKI3:string="iBeastSki3"
	export const OTHER_IBEASTSKI4:string="iBeastSki4"
	export const OTHER_ICASH:string="iCash"
	export const OTHER_IEXPTSKI1:string="iExptSki1"
	export const OTHER_IEXPTSKI2:string="iExptSki2"
	export const OTHER_IEXPTSKI3:string="iExptSki3"
	export const OTHER_IEXPTSKI4:string="iExptSki4"
	export const OTHER_IEXPTSKI5:string="iExptSki5"
	export const OTHER_IGOODNESS:string="iGoodness"
	export const OTHER_IGRADE:string="iGrade"
	export const OTHER_IICON:string="iIcon"
	export const OTHER_IMAXEXPT1:string="iMaxExpt1"
	export const OTHER_IMAXEXPT2:string="iMaxExpt2"
	export const OTHER_IMAXEXPT3:string="iMaxExpt3"
	export const OTHER_IMAXEXPT4:string="iMaxExpt4"
	export const OTHER_IMAXEXPT5:string="iMaxExpt5"
	export const OTHER_IORGOFFER:string="iOrgOffer"
	export const OTHER_ISAVING:string="iSaving"
	export const OTHER_ISCHOFFER:string="iSchOffer"
	export const OTHER_ISCHOOL:string="iSchool"
	export const OTHER_IUPEXP:string="iUpExp"
	export const OTHER_IZHUANZHI:string="iZhuanZhi"
	export const OTHER_PET_XIULIAN:string="pet_xiulian"
	export const OTHER_SUMMARY:string="summary"
	export const OTHER_USERNUM:string="usernum"
	export const OTHER_XIANYU:string="xianyu"
	export const OTHER_XIULIAN:string="xiulian"

	export const COMMON_KEY_CHUBEI_RATE=100001
	export const COMMON_KEY_BB_XIU_EXP_TO_COIN=100002
	export const COMMON_KEY_XIANYU_TO_DOT=100003
	export const COMMON_KEY_SKILL_SCHOOL_MAX=200001


	export const SKILL_TYPE_SCHOOL=1
	export const SKILL_TYPE_BANGPAI=2
}